#pragma once
#define WIN32_LEAN_AND_MEAN
#define NOMINMAX
#include <Windows.h>
#include <Psapi.h>
#include <cstdint>
#include <iomanip>
#include <iostream>
#include <string>
#include <fstream>
#include <ostream>
#include <istream>
#include <ctime>
#include <thread>
#include <chrono>
#include <atomic>
#include <mutex>
#include <cassert>
